import localFont from "next/font/local";
import Script from "next/script";
import { Slide, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import TopBar from "@/components/layout/TopBar/TopBar.jsx";
import Navbar from "@/components/layout/Navbar/Navbar.jsx";
import Footer from "@/components/layout/Footer/Footer.jsx";
import APICall from "@/components/shared/buttons/APICall.jsx";

const inter = localFont({
  src: "../assets/fonts/Inter-VariableFont.ttf",
  display: "swap",
});

const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL || "https://outsourceaccountings.co.uk";

export const metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "Outsource Accounting | Professional Accounting Services UK",
    template: "%s | Outsource Accounting",
  },
  description:
    "Expert outsourced accounting services for UK businesses — Annual Accounts, Self Assessment, Payroll, VAT, Bookkeeping, Corporation Tax & Company Formation.",
  keywords: [
    // Core brand
    "outsource accounting",
    "outsource accountings",
    "outsourceaccountings",
    "outsourceaccountings.co.uk",
    "outsource accountant UK",
    "outsourced accounting services",
    "outsourced accounting firm UK",
    "outsourced accountant",
    "accounting outsourcing UK",
    "outsource accounting services UK",
    "professional accounting services UK",
    "UK outsourced accounting",
    "outsource accounting UK",
    "outsource accounts UK",
    "outsource my accounting UK",
    "outsource accounting department UK",
    "outsource finance and accounting UK",
    "outsource accounting team UK",
    "outsource accounting staff UK",
    "outsource accountant services",
    "outsourcing accounting UK",
    "outsource bookkeeping and accounting UK",
    "outsource tax returns UK",
    "outsource payroll and accounting UK",
    "best outsourced accounting UK",
    "top outsourced accounting firm UK",
    "trusted outsourced accounting UK",
    "outsource accounting for small business UK",
    "outsource accounting for startups UK",
    "outsource accounting for limited company UK",
    "outsource accounting for sole trader UK",
    "outsource accounting for landlords UK",
    "outsource accounting for contractors UK",
    "outsource accounting for freelancers UK",
    "outsource accounting for ecommerce UK",
    "outsource accounting London",
    "outsource accounting Manchester",
    "outsource accounting Birmingham",
    "outsource accounting Leeds",
    "outsource accounting Bristol",
    // Competitors - online accountants UK
    "alternative to Crunch accounting",
    "Crunch accounting UK",
    "better than Crunch accounting",
    "alternative to FreeAgent",
    "FreeAgent accountant UK",
    "alternative to Gorilla Accounting",
    "Gorilla Accounting UK",
    "alternative to Inniaccounts",
    "Inniaccounts UK",
    "alternative to Qdos Accounting",
    "Qdos Accounting UK",
    "alternative to Nixon Williams",
    "Nixon Williams accountant UK",
    "alternative to SJD Accountancy",
    "SJD Accountancy UK",
    "alternative to TaxAssist",
    "TaxAssist Accountants UK",
    "alternative to The Accountancy Partnership",
    "The Accountancy Partnership UK",
    "alternative to DNS Accountants",
    "DNS Accountants UK",
    "alternative to QAccounting",
    "QAccounting UK",
    "alternative to Clear House Accountants",
    "Clear House Accountants UK",
    "alternative to Pearl Lemon Accountants",
    "Pearl Lemon Accountants UK",
    "alternative to Azets",
    "Azets accounting UK",
    "alternative to Xeinadin",
    "Xeinadin accounting UK",
    "alternative to MHA MacIntyre Hudson",
    "MHA accounting UK",
    "alternative to Haines Watts",
    "Haines Watts accountant UK",
    "alternative to Mazars UK",
    "Mazars accounting UK",
    "alternative to BDO UK",
    "BDO accountant UK",
    "alternative to Grant Thornton UK",
    "Grant Thornton accounting UK",
    "alternative to PKF",
    "PKF accounting UK",
    "alternative to Menzies LLP",
    "Menzies accounting UK",
    "alternative to Begbies Traynor",
    "Begbies Traynor UK",
    "alternative to Larking Gowen",
    "Larking Gowen accountant UK",
    "alternative to Albert Goodman",
    "Albert Goodman accountant UK",
    "alternative to Accounts and Legal",
    "Accounts and Legal UK",
    "alternative to Outbooks",
    "Outbooks outsourced bookkeeping UK",
    "alternative to QXFAS",
    "QXFAS outsourced accounting UK",
    "alternative to Cogneesol",
    "Cogneesol accounting UK",
    "alternative to Countingup",
    "Countingup UK",
    "alternative to Ember accounting",
    "Ember accounting UK",
    "alternative to 1Accounts",
    "1Accounts UK",
    "alternative to Raffingers",
    "Raffingers accountant UK",
    "alternative to Coconut accounting",
    "Coconut accounting UK",
    "cheaper than Crunch accounting",
    "cheaper than TaxAssist",
    "cheaper than SJD Accountancy",
    "cheaper alternative to online accountant UK",
    "best alternative to online accountant UK",
    // Annual accounts
    "annual accounts UK",
    "annual accounts preparation",
    "annual accounts filing",
    "statutory accounts UK",
    "company annual accounts",
    "limited company accounts",
    "prepare annual accounts UK",
    "annual accounts filing service",
    "Companies House accounts",
    "year end accounts UK",
    "year end accounts preparation",
    "accounts preparation service",
    "statutory financial statements UK",
    "dormant company accounts",
    "micro entity accounts UK",
    "small company accounts UK",
    "abbreviated accounts UK",
    "annual return filing UK",
    "confirmation statement filing",
    "directors report UK",
    // Self assessment
    "self assessment tax return",
    "self assessment UK",
    "self employed tax return",
    "personal tax return UK",
    "HMRC self assessment",
    "file self assessment online",
    "self assessment accountant",
    "sole trader tax return",
    "self assessment tax return filing",
    "self assessment deadline",
    "self assessment 2025 2026",
    "self assessment registration UK",
    "self assessment late filing",
    "self assessment penalty",
    "self assessment income tax",
    "self employed income tax UK",
    "sole trader accounts UK",
    "self assessment help UK",
    "tax return submission UK",
    "online tax return UK",
    // Bookkeeping
    "bookkeeping services UK",
    "online bookkeeping UK",
    "small business bookkeeping",
    "bookkeeper UK",
    "cloud bookkeeping",
    "Xero bookkeeping",
    "QuickBooks bookkeeping",
    "monthly bookkeeping service",
    "bookkeeping for small business",
    "virtual bookkeeper UK",
    "remote bookkeeping services",
    "bookkeeping and accounting UK",
    "bookkeeping outsourcing UK",
    "outsourced bookkeeping UK",
    "bookkeeper for small business UK",
    "affordable bookkeeping UK",
    "bookkeeping services for startups",
    "daily bookkeeping UK",
    "weekly bookkeeping UK",
    "annual bookkeeping UK",
    // Payroll
    "payroll services UK",
    "managed payroll UK",
    "outsourced payroll UK",
    "payroll bureau UK",
    "small business payroll",
    "PAYE payroll UK",
    "RTI payroll submissions",
    "payroll processing UK",
    "auto enrolment pension payroll",
    "payroll management UK",
    "payroll outsourcing UK",
    "weekly payroll UK",
    "monthly payroll UK",
    "payroll for small business UK",
    "employee payroll UK",
    "payroll compliance UK",
    "payslip preparation UK",
    "P60 preparation UK",
    "P11D preparation UK",
    "P45 processing UK",
    "CIS payroll UK",
    "construction payroll UK",
    "umbrella company payroll UK",
    "PAYE registration UK",
    "employer PAYE UK",
    // VAT
    "VAT returns UK",
    "VAT registration UK",
    "VAT accountant UK",
    "Making Tax Digital VAT",
    "MTD VAT",
    "quarterly VAT returns",
    "VAT advice UK",
    "flat rate VAT scheme",
    "VAT return preparation",
    "VAT compliance UK",
    "VAT investigation UK",
    "VAT reclaim UK",
    "VAT deregistration UK",
    "monthly VAT returns",
    "annual VAT accounting scheme",
    "VAT threshold UK",
    "when to register for VAT UK",
    "reverse charge VAT UK",
    "import VAT UK",
    "VAT on property UK",
    "partial exemption VAT UK",
    "VAT inspection UK",
    "VAT accountant London",
    "VAT accountant Manchester",
    "submit VAT return online UK",
    // Corporation tax
    "corporation tax UK",
    "corporation tax return",
    "CT600 filing",
    "company tax return UK",
    "corporation tax accountant",
    "corporate tax planning UK",
    "small business corporation tax",
    "limited company tax return",
    "corporation tax deadline UK",
    "corporation tax rate UK",
    "corporation tax relief UK",
    "R&D tax credits UK",
    "research and development tax relief UK",
    "capital allowances UK",
    "annual investment allowance UK",
    "corporation tax losses UK",
    "group relief corporation tax",
    "patent box UK",
    "creative industry tax relief UK",
    "entrepreneurs relief UK",
    // Company formation
    "company formation UK",
    "register a company UK",
    "limited company formation",
    "Companies House registration",
    "set up limited company UK",
    "company incorporation UK",
    "start a limited company",
    "new company registration UK",
    "company formation agent UK",
    "online company formation UK",
    "same day company formation UK",
    "ready made company UK",
    "company secretarial services UK",
    "registered office address UK",
    "company director services UK",
    "LLP formation UK",
    "limited liability partnership UK",
    "partnership formation UK",
    "business registration UK",
    "company name registration UK",
    // General accounting services
    "accounting services UK",
    "accounting firm UK",
    "small business accountant UK",
    "accountant for small business",
    "cheap accountant UK",
    "affordable accountant UK",
    "online accountant UK",
    "remote accountant UK",
    "virtual accountant UK",
    "business accounting services",
    "HMRC accountant UK",
    "tax accountant UK",
    "chartered accountant UK",
    "certified accountant UK",
    "ACCA accountant UK",
    "CIMA accountant UK",
    "AAT accountant UK",
    "ICB bookkeeper UK",
    "accounting consultancy UK",
    "management accounting UK",
    "financial accounting UK",
    "cost accounting UK",
    "business advisory UK",
    "accounting for ecommerce UK",
    "accounting for Amazon sellers UK",
    "accounting for eBay sellers UK",
    "accounting for online business UK",
    // Industry specific
    "construction accountant UK",
    "property accountant UK",
    "retail accountant UK",
    "restaurant accountant UK",
    "hospitality accountant UK",
    "healthcare accountant UK",
    "medical practice accountant UK",
    "dental practice accountant UK",
    "GP accountant UK",
    "law firm accountant UK",
    "solicitor accountant UK",
    "IT contractor accountant UK",
    "technology company accountant UK",
    "creative agency accountant UK",
    "marketing agency accountant UK",
    "recruitment agency accountant UK",
    "manufacturing accountant UK",
    "farming accountant UK",
    "agricultural accountant UK",
    "charity accountant UK",
    "not-for-profit accountant UK",
    "CIC accountant UK",
    "landlord accountant UK",
    "property investor accountant UK",
    "buy-to-let accountant UK",
    "HMO accountant UK",
    "Airbnb accountant UK",
    "holiday let accountant UK",
    "letting agent accountant UK",
    // UK cities - England
    "accountant London",
    "accountant Manchester",
    "accountant Birmingham",
    "accountant Leeds",
    "accountant Sheffield",
    "accountant Bristol",
    "accountant Liverpool",
    "accountant Newcastle",
    "accountant Nottingham",
    "accountant Southampton",
    "accountant Leicester",
    "accountant Coventry",
    "accountant Bradford",
    "accountant Hull",
    "accountant Plymouth",
    "accountant Wolverhampton",
    "accountant Derby",
    "accountant Oxford",
    "accountant Cambridge",
    "accountant Reading",
    "accountant Milton Keynes",
    "accountant Norwich",
    "accountant Brighton",
    "accountant Sunderland",
    "accountant Middlesbrough",
    "accountant Peterborough",
    "accountant York",
    "accountant Exeter",
    "accountant Gloucester",
    "accountant Luton",
    "accountant Northampton",
    "accountant Blackpool",
    "accountant Bolton",
    "accountant Swindon",
    "accountant Bournemouth",
    "accountant Huddersfield",
    "accountant Stockport",
    "accountant Warrington",
    // UK cities - Scotland, Wales, NI
    "accountant Edinburgh",
    "accountant Glasgow",
    "accountant Cardiff",
    "accountant Belfast",
    "accountant Aberdeen",
    "accountant Dundee",
    "accountant Swansea",
    "accountant Newport",
    "accountant Inverness",
    "accountant Stirling",
    // Location + service combos
    "online accountant London",
    "online accountant Manchester",
    "online accountant Birmingham",
    "remote accountant London",
    "outsourced accounting London",
    "outsourced accounting Manchester",
    "small business accountant London",
    "small business accountant Manchester",
    "accounting services London",
    "accounting services Manchester",
    "accounting services Birmingham",
    "accounting services Leeds",
    "accounting services Bristol",
    "bookkeeping London",
    "bookkeeping Manchester",
    "bookkeeping Birmingham",
    "payroll services London",
    "payroll services Manchester",
    "VAT returns London",
    "VAT returns Manchester",
    "self assessment London",
    "self assessment Manchester",
    "corporation tax London",
    "company formation London",
    "company formation Birmingham",
    // Cloud / software
    "Xero accountant UK",
    "QuickBooks accountant UK",
    "Sage accounting UK",
    "FreeAgent accountant UK",
    "Kashflow accounting UK",
    "cloud accounting UK",
    "online accounting software UK",
    "Xero certified advisor UK",
    "Xero migration service UK",
    "QuickBooks Online UK",
    "cloud accounting migration UK",
    "paperless accounting UK",
    "automated bookkeeping UK",
    "digital accounting UK",
    "Xero setup UK",
    "QuickBooks setup UK",
    "Sage setup UK",
    "accounting software advice UK",
    // Tax types
    "income tax UK",
    "capital gains tax UK",
    "capital gains tax return UK",
    "inheritance tax UK",
    "inheritance tax planning UK",
    "stamp duty UK",
    "IR35 UK",
    "IR35 accountant UK",
    "off-payroll working UK",
    "CIS tax UK",
    "construction industry scheme UK",
    "CIS returns UK",
    "CIS refund UK",
    "dividend tax UK",
    "dividend allowance UK",
    "national insurance contributions UK",
    "class 2 national insurance UK",
    "class 4 national insurance UK",
    "employer national insurance UK",
    "SDLT UK",
    "stamp duty land tax UK",
    "pension tax relief UK",
    "enterprise investment scheme UK",
    "EIS tax relief UK",
    "SEIS tax relief UK",
    "R&D tax credits UK",
    "tax relief UK",
    "tax allowances UK",
    "personal allowance UK",
    "marriage allowance UK",
    "trading allowance UK",
    "property allowance UK",
    "business asset disposal relief UK",
    // HMRC specific
    "HMRC registration UK",
    "HMRC tax enquiry UK",
    "HMRC tax investigation UK",
    "HMRC penalty appeal UK",
    "HMRC disclosure UK",
    "HMRC compliance check UK",
    "HMRC payment plan UK",
    "time to pay arrangement UK",
    "HMRC debt management",
    "HMRC VAT investigation UK",
    "HMRC corporation tax enquiry",
    "voluntary disclosure HMRC",
    "tax investigation insurance UK",
    "HMRC online filing UK",
    "HMRC agent services UK",
    "tax agent UK",
    // Making Tax Digital
    "Making Tax Digital UK",
    "MTD ITSA UK",
    "MTD income tax UK",
    "Making Tax Digital for income tax UK",
    "MTD for corporation tax UK",
    "digital records HMRC UK",
    "MTD compatible software UK",
    "bridging software MTD UK",
    "MTD submission UK",
    "quarterly updates HMRC UK",
    "Making Tax Digital accountant UK",
    "MTD deadline UK",
    "MTD for landlords UK",
    "MTD for self employed UK",
    "MTD compliance UK",
    // Financial services
    "financial reporting UK",
    "management accounts UK",
    "cash flow management UK",
    "cash flow forecast UK",
    "cash flow statement UK",
    "profit and loss statement UK",
    "balance sheet preparation UK",
    "financial statements UK",
    "interim accounts UK",
    "monthly management accounts UK",
    "quarterly management accounts UK",
    "board reports UK",
    "KPI reporting UK",
    "financial dashboard UK",
    "budgeting and forecasting UK",
    "business plan accounting UK",
    "financial projections UK",
    "business valuation UK",
    "due diligence accounting UK",
    "accounts payable management UK",
    "accounts receivable management UK",
    "credit control services UK",
    "working capital management UK",
    // Audience types
    "accountant for freelancers UK",
    "accountant for contractors UK",
    "accountant for sole traders",
    "accountant for startups UK",
    "accountant for landlords UK",
    "accountant for new businesses UK",
    "accountant for growing businesses UK",
    "accountant for limited companies UK",
    "accountant for partnerships UK",
    "accountant for entrepreneurs UK",
    "accountant for self employed UK",
    "accountant for investors UK",
    "accountant for directors UK",
    "accountant for high earners UK",
    "accountant for non-residents UK",
    "accountant for expats UK",
    // Pensions & benefits
    "auto enrolment pension UK",
    "workplace pension UK",
    "pension auto enrolment accounting",
    "employer pension contributions UK",
    "pension scheme setup UK",
    "benefits in kind UK",
    "P11D filing UK",
    "company car tax UK",
    "salary sacrifice accounting UK",
    "employee benefits accounting UK",
    "expense claims accounting UK",
    "mileage claims UK",
    "home office expenses UK",
    "work from home expenses UK",
    // International / expat
    "UK non-resident tax return",
    "international tax UK",
    "cross-border tax UK",
    "UK expat tax return",
    "overseas income UK tax",
    "foreign income tax UK",
    "double taxation treaty UK",
    "withholding tax UK",
    "transfer pricing UK",
    "non-domiciled UK tax",
    "remittance basis UK tax",
    // Ecommerce specific
    "ecommerce accountant UK",
    "Amazon FBA accountant UK",
    "eBay seller accountant UK",
    "Shopify accountant UK",
    "WooCommerce accountant UK",
    "dropshipping accountant UK",
    "online store accountant UK",
    "marketplace seller accountant UK",
    "ecommerce VAT UK",
    "ecommerce bookkeeping UK",
    "ecommerce tax return UK",
    "overseas seller UK VAT",
    // Property specific
    "property accountant UK",
    "buy-to-let tax return UK",
    "rental income accountant UK",
    "HMO tax return UK",
    "property investment accountant UK",
    "property developer accountant UK",
    "property portfolio accountant UK",
    "property capital gains tax UK",
    "mortgage interest relief UK",
    "section 24 tax UK",
    "property income tax UK",
    // Construction specific
    "construction accountant UK",
    "CIS accountant UK",
    "subcontractor accountant UK",
    "main contractor accountant UK",
    "builders accountant UK",
    "plumber accountant UK",
    "electrician accountant UK",
    "roofer accountant UK",
    "CIS monthly return UK",
    "CIS deductions UK",
    "construction VAT reverse charge UK",
    // Healthcare specific
    "GP practice accountant UK",
    "NHS accountant UK",
    "medical accountant UK",
    "dental accountant UK",
    "optician accountant UK",
    "care home accountant UK",
    "pharmacy accountant UK",
    "private clinic accountant UK",
    "NHS pension accountant UK",
    "locum accountant UK",
    "locum tax return UK",
    "agency nurse accountant UK",
    // Startups / growth
    "startup accountant UK",
    "early stage startup accounting UK",
    "pre-revenue startup accountant UK",
    "startup CFO services UK",
    "fractional CFO UK",
    "outsourced CFO UK",
    "virtual CFO UK",
    "chief financial officer outsourcing UK",
    "finance director outsourcing UK",
    "FD outsourcing UK",
    "growth accounting UK",
    "scale-up accounting UK",
    "high growth business accountant UK",
    // Compliance / regulatory
    "Companies House filing UK",
    "confirmation statement UK",
    "company dissolution UK",
    "dormant company accounting UK",
    "company secretary services UK",
    "registered office service UK",
    "statutory books UK",
    "company changes Companies House",
    "FRS 102 UK",
    "FRS 105 UK",
    "UK GAAP accounting",
    // Pricing / value
    "cheap accounting services UK",
    "low cost accountant UK",
    "fixed fee accountant UK",
    "fixed price accounting UK",
    "flat fee accounting UK",
    "accounting packages UK",
    "accounting subscription UK",
    "monthly accounting fee UK",
    "accountant fees UK",
    "no hidden fees accountant UK",
    "transparent accounting fees UK",
    // Trust / quality
    "trusted accountant UK",
    "reliable accountant UK",
    "experienced accountant UK",
    "qualified accountant UK",
    "regulated accountant UK",
    "ICAEW accountant UK",
    "ACCA registered accountant UK",
    "AAT qualified accountant UK",
    "5 star accountant UK",
    "highly rated accountant UK",
    "recommended accountant UK",
    // Niche / special services
    "tax investigation support UK",
    "HMRC dispute resolution UK",
    "late tax return filing UK",
    "catch up bookkeeping UK",
    "back years accounting UK",
    "previous years tax return UK",
    "tax return amendment UK",
    "probate accounting UK",
    "trust accounting UK",
    "estate planning accountant UK",
    "director loan account UK",
    "overdrawn director loan UK",
    "company dividend payment UK",
    "dividend voucher UK",
    "shareholder accounting UK",
    // Gig economy / self-employed professions
    "IR35 review service UK",
    "personal service company accounting UK",
    "PSC accountant UK",
    "gig economy accountant UK",
    "self-employed delivery driver accountant UK",
    "taxi driver accountant UK",
    "private hire accountant UK",
    "courier accountant UK",
    // Creative / freelance professions
    "musician accountant UK",
    "artist accountant UK",
    "actor accountant UK",
    "influencer accountant UK",
    "YouTuber accountant UK",
    "content creator accountant UK",
    "blogger accountant UK",
    "podcaster accountant UK",
    "copywriter accountant UK",
    "graphic designer accountant UK",
    "web designer accountant UK",
    "software developer accountant UK",
    "photographer accountant UK",
    "videographer accountant UK",
    "wedding photographer accountant UK",
    // Health & wellness professions
    "personal trainer accountant UK",
    "fitness instructor accountant UK",
    "yoga teacher accountant UK",
    "massage therapist accountant UK",
    "beautician accountant UK",
    "hairdresser accountant UK",
    "barber accountant UK",
    "therapist accountant UK",
    "counsellor accountant UK",
    "psychologist accountant UK",
    "childminder accountant UK",
    "foster carer tax return UK",
    "supply teacher accountant UK",
    "tutoring income tax UK",
    "virtual assistant accountant UK",
    // Digital marketing professions
    "social media manager accountant UK",
    "digital marketer accountant UK",
    "SEO consultant accountant UK",
    "PR consultant accountant UK",
    "life coach accountant UK",
    "business coach accountant UK",
    // Finance outsourcing
    "back-office accounting UK",
    "finance and accounting outsourcing UK",
    "accounting process outsourcing UK",
    "BPO accounting UK",
    "outsourced finance team UK",
    "shared services accounting UK",
    "finance function outsourcing UK",
    "fractional accountant UK",
    "part-time accountant UK",
    "interim accountant UK",
    // Timing / urgency
    "same day accounting UK",
    "urgent accounting UK",
    "last minute tax return UK",
    "emergency accountant UK",
    "tax deadline help UK",
    "January 31 deadline accountant",
    "tax year end accountant",
    "financial year end accounting UK",
    "Making Tax Digital deadline 2026",
    "MTD ITSA April 2026 UK",
    // International business
    "UK subsidiary accounting",
    "overseas parent company UK",
    "UK branch accounting",
    "double tax agreement UK",
    "tax treaty UK",
    "transfer pricing documentation UK",
    "FATCA compliance UK",
    "CRS compliance UK",
    "international accounting UK",
    // Sector-specific tax reliefs
    "film tax relief UK",
    "video games tax relief UK",
    "theatre tax relief UK",
    "animation tax relief UK",
    "R&D tax claim UK",
    "ATED returns UK",
    "non-resident landlord scheme UK",
    "SIPP accounting UK",
    "SSAS accounting UK",
    "pension fund accounting UK",
    // Group / consolidated accounts
    "consolidated accounts UK",
    "group accounts UK",
    "holding company accounts UK",
    "subsidiary accounts UK",
    "joint venture accounting UK",
    "partnership accounts UK",
    "LLP accounts UK",
    // Bundled services
    "accounting and payroll UK",
    "bookkeeping and payroll UK",
    "VAT and payroll UK",
    "accounting and VAT UK",
    "tax and accounting UK",
    "bookkeeping and tax UK",
    "all-inclusive accounting service UK",
    "full service accounting UK",
    "complete accounting package UK",
    "sole trader accounting package UK",
    "limited company accounting package UK",
    // Discovery / search intent
    "accountant near me UK",
    "local accountant UK",
    "find accountant UK",
    "hire accountant UK",
    "accounting help UK",
    "accounting support UK",
    "accounting advice UK",
    "accounting consultation UK",
    "free accounting consultation UK",
    "switch accountant UK",
    "change accountant UK",
    "UK tax advice",
    "UK tax help",
    "UK tax support",
    "small business tax advice UK",
    "startup accounting advice UK",
    "business tax advice UK",
    "HMRC compliance UK",
    "tax compliance UK",
    "tax planning UK",
    "year end accounts",
  ],
  verification: {
    google: "LXLD34lW_HVnOLdPsBFJ6yvGHQ0P62DJO3AWJg-xJIo",
  },
  authors: [{ name: "Outsource Accounting" }],
  creator: "Outsource Accounting",
  publisher: "Outsource Accounting",
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  alternates: {
    canonical: siteUrl,
  },
  openGraph: {
    type: "website",
    locale: "en_GB",
    url: siteUrl,
    siteName: "Outsource Accounting",
    title: "Outsource Accounting | Professional Accounting Services UK",
    description:
      "Expert outsourced accounting services for UK businesses — Annual Accounts, Self Assessment, Payroll, VAT, Bookkeeping, Corporation Tax & Company Formation.",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Outsource Accounting - Professional Accounting Services UK",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Outsource Accounting | Professional Accounting Services UK",
    description:
      "Expert outsourced accounting services for UK businesses — Annual Accounts, Self Assessment, Payroll, VAT & more.",
    images: ["/og-image.png"],
  },
};

const siteSchema = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "AccountingService",
      "@id": `${siteUrl}/#organization`,
      name: "Outsource Accounting",
      url: siteUrl,
      logo: {
        "@type": "ImageObject",
        url: `${siteUrl}/og-image.png`,
      },
      description:
        "Expert outsourced accounting services for UK businesses — Annual Accounts, Self Assessment, Payroll, VAT, Bookkeeping, Corporation Tax & Company Formation.",
      areaServed: "GB",
      serviceType: [
        "Annual Accounts",
        "Self Assessment",
        "Bookkeeping",
        "Payroll",
        "VAT Returns",
        "Company Formation",
        "Corporation Tax",
      ],
      contactPoint: {
        "@type": "ContactPoint",
        contactType: "customer service",
        areaServed: "GB",
        availableLanguage: "English",
      },
    },
    {
      "@type": "WebSite",
      "@id": `${siteUrl}/#website`,
      url: siteUrl,
      name: "Outsource Accounting",
      publisher: { "@id": `${siteUrl}/#organization` },
      potentialAction: {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: `${siteUrl}/blogs?search={search_term_string}`,
        },
        "query-input": "required name=search_term_string",
      },
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(siteSchema) }}
        />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-JVX03L2MCN"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-JVX03L2MCN');
          `}
        </Script>
        <TopBar />
        <Navbar
          buyNowSlot={<APICall />}
          mobileBuyNowSlot={<APICall mobile />}
        />
        {children}
        <Footer />

        <ToastContainer
          position="bottom-right"
          autoClose={8000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Slide}
        />
      </body>
    </html>
  );
}
